language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-progress --no-plugins

script: phpunit --configuration phpunit.xml

notifications:
    on_success: never
    on_failure: always
