language: php

sudo: false

php:
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-progress --no-plugins

script: phpunit --coverage-text --coverage-clover=coverage.clover
